Insignia_Delta3: Drop `audio_effects.conf`
frameworks/av/services/audiopolicy/managerdefault/AudioPolicyManager.cpp:4305:2: error: Audio policy no longer supports legacy .conf configuration format
'#error Audio policy no longer supports legacy .conf configuration format'